FROM python:stretch
MAINTAINER Matteo Gaito

ADD code/requirements.txt /etc/tony-requirements.txt

RUN mkdir /tony
RUN apt-get update && apt-get install locales
RUN echo "it_IT.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen

RUN apt-get install -y libxss1 libappindicator1 wget
RUN apt-get install -y fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libnspr4 libnss3 libxtst6 lsb-release xdg-utils
RUN apt-get install -y xvfb
RUN echo "deb http://security.debian.org/debian-security stretch/updates main" >> /etc/apt/sources.list
RUN apt-get update
RUN apt-get install chromium-browser -y

RUN pip3 install -r /etc/tony-requirements.txt

EXPOSE 5000

CMD ["/usr/local/bin/gunicorn", "-c", "/tony/sys/gunicorn_conf.py", "--chdir", "/tony", "tony:app", "--preload"]
